// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_ChatBox;
lv_obj_t * uic_Send;
lv_obj_t * uic_Chat;
lv_obj_t * ui_Chat = NULL;
lv_obj_t * ui_Input = NULL;
lv_obj_t * ui_Send = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_ChatBox = NULL;
// event funtions
void ui_event_Send(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        send(e);
    }
}

// build funtions

void ui_Chat_screen_init(void)
{
    ui_Chat = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Chat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Input = lv_textarea_create(ui_Chat);
    lv_obj_set_width(ui_Input, 249);
    lv_obj_set_height(ui_Input, 70);
    lv_obj_set_x(ui_Input, 73);
    lv_obj_set_y(ui_Input, 15);
    lv_obj_set_align(ui_Input, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Input, "Placeholder...");
    lv_obj_clear_flag(ui_Input, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    ui_Send = lv_btn_create(ui_Chat);
    lv_obj_set_width(ui_Send, 100);
    lv_obj_set_height(ui_Send, 50);
    lv_obj_set_x(ui_Send, -157);
    lv_obj_set_y(ui_Send, 14);
    lv_obj_set_align(ui_Send, LV_ALIGN_CENTER);

    ui_Label2 = lv_label_create(ui_Send);
    lv_obj_set_width(ui_Label2, lv_pct(100));
    lv_obj_set_height(ui_Label2, lv_pct(100));
    lv_obj_set_x(ui_Label2, 10);
    lv_obj_set_y(ui_Label2, 8);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Send");

    ui_Keyboard1 = lv_keyboard_create(ui_Chat);
    lv_obj_set_width(ui_Keyboard1, 480);
    lv_obj_set_height(ui_Keyboard1, 160);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 160);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_ChatBox = lv_textarea_create(ui_Chat);
    lv_obj_set_width(ui_ChatBox, 369);
    lv_obj_set_height(ui_ChatBox, 179);
    lv_obj_set_x(ui_ChatBox, -7);
    lv_obj_set_y(ui_ChatBox, -133);
    lv_obj_set_align(ui_ChatBox, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_ChatBox, "Hello user");
    lv_textarea_set_placeholder_text(ui_ChatBox, "Placeholder...");
    lv_obj_clear_flag(ui_ChatBox, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    lv_obj_add_event_cb(ui_Send, ui_event_Send, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_Input);
    uic_Chat = ui_Chat;
    uic_Send = ui_Send;
    uic_ChatBox = ui_ChatBox;

}

void ui_Chat_screen_destroy(void)
{
    if(ui_Chat) lv_obj_del(ui_Chat);

    // NULL screen variables
    uic_Chat = NULL;
    ui_Chat = NULL;
    ui_Input = NULL;
    uic_Send = NULL;
    ui_Send = NULL;
    ui_Label2 = NULL;
    ui_Keyboard1 = NULL;
    uic_ChatBox = NULL;
    ui_ChatBox = NULL;

}
