// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_CHAT_H
#define UI_CHAT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Chat
extern void ui_Chat_screen_init(void);
extern void ui_Chat_screen_destroy(void);
extern lv_obj_t * ui_Chat;
extern lv_obj_t * ui_Input;
extern void ui_event_Send(lv_event_t * e);
extern lv_obj_t * ui_Send;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_ChatBox;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Chat;
extern lv_obj_t * uic_Send;
extern lv_obj_t * uic_ChatBox;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

