// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_WifiText;
lv_obj_t * uic_Wifi;
lv_obj_t * ui_Wifi = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_WifiText = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        go(e);
    }
}

// build funtions

void ui_Wifi_screen_init(void)
{
    ui_Wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard2 = lv_keyboard_create(ui_Wifi);
    lv_obj_set_width(ui_Keyboard2, 480);
    lv_obj_set_height(ui_Keyboard2, 160);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 160);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_WifiText = lv_textarea_create(ui_Wifi);
    lv_obj_set_width(ui_WifiText, 421);
    lv_obj_set_height(ui_WifiText, 228);
    lv_obj_set_x(ui_WifiText, 0);
    lv_obj_set_y(ui_WifiText, -100);
    lv_obj_set_align(ui_WifiText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WifiText, "Wifi name (password on the next line if needed)...");

    ui_Button2 = lv_btn_create(ui_Wifi);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 37);
    lv_obj_set_x(ui_Button2, -2);
    lv_obj_set_y(ui_Button2, 48);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -3);
    lv_obj_set_y(ui_Label3, 2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Go");

    lv_keyboard_set_textarea(ui_Keyboard2, ui_WifiText);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    uic_Wifi = ui_Wifi;
    uic_WifiText = ui_WifiText;

}

void ui_Wifi_screen_destroy(void)
{
    if(ui_Wifi) lv_obj_del(ui_Wifi);

    // NULL screen variables
    uic_Wifi = NULL;
    ui_Wifi = NULL;
    ui_Keyboard2 = NULL;
    uic_WifiText = NULL;
    ui_WifiText = NULL;
    ui_Button2 = NULL;
    ui_Label3 = NULL;

}
