// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Wifi
extern void ui_Wifi_screen_init(void);
extern void ui_Wifi_screen_destroy(void);
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_WifiText;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Wifi;
extern lv_obj_t * uic_WifiText;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

