// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Wifi = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        abc_xyz(e);
    }
}

// build funtions

void ui_Wifi_screen_init(void)
{
    ui_Wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_Wifi);
    lv_obj_set_width(ui_Button3, 173);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, -55);
    lv_obj_set_y(ui_Button3, -62);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, lv_pct(100));
    lv_obj_set_height(ui_Label3, lv_pct(100));
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Wifi_screen_destroy(void)
{
    if(ui_Wifi) lv_obj_del(ui_Wifi);

    // NULL screen variables
    ui_Wifi = NULL;
    ui_Button3 = NULL;
    ui_Label3 = NULL;

}
